### ISSUE TITLE
Issues with 8x8 matrix displays

### ISSUE THREAD

**Issue by joewez** [adafruit/micropython-adafruit-bitmap-font#3]
I am having rendering problems with an 8x8 LED matrix display using the latest code.  The display "partially" works in that some of the letters are rendered correctly.  It's the scrolling and split letters that seem to be rendered in the wrong columns.

I believe it has to do with the algorithm for computing character positions.  I think it fails with such a short width for an LED matrix.

**Comment by joewez** [comment]
After some debugging, it looks like the fix is in the range used to iterate through the columns of the character being displayed. 

![suggest](https://user-images.githubusercontent.com/7892212/31311928-b07c1a5c-ab7c-11e7-9ed9-6c362d1aaa7f.jpg)

Only a partial set of the columns are actually displayed when the character is partially off the matrix.

Anyway, hope this helps.

**Comment by genkagen** [comment]
Excellent!! Thanks @joewez , your codes help me a lot. I am working on a 16 x 8 neopixel with an ESP32 port

**Comment by ladyada** [comment]
hiya, we'll be archiving this repo, we're not supporting micropython code.

we've integrated a bunch of this font stuff into our soft framebuf implementation for circuitpython https://github.com/adafruit/Adafruit_CircuitPython_framebuf

if you can use adafruit_framebuf for your underlying display, then you will get this font :)
