### ISSUE TITLE
CircuitPython uses struct not ustruct

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/micropython-adafruit-bitmap-font#6]
the current Circuit Python builds had the module stuct built-in.
To use this library it is necessary to import struct as ustruct
submitted #5 to implement this

**Comment by ladyada** [comment]
hiya - ive joined this into framebuf cause i feel like if you're going to draw text, you'll want lines and pixels too!
i've also fixed the ustruct thingy
https://github.com/adafruit/Adafruit_CircuitPython_framebuf
